STRING( TIMESTAMP stop_time "%d|%H|%M|%S" )
FILE( READ "${filename}" start_time )
STRING( REPLACE "|" ";" start_time "${start_time}" )
STRING( REPLACE "|" ";" stop_time  "${stop_time}"  )
LIST(GET start_time 0 day1 )
LIST(GET stop_time  0 day2 )
LIST(GET start_time 1 hour1 )
LIST(GET stop_time  1 hour2 )
LIST(GET start_time 2 min1 )
LIST(GET stop_time  2 min2 )
LIST(GET start_time 3 sec1 )
LIST(GET stop_time  3 sec2 )
MATH(EXPR diff "(((${day2}-${day1})*24+(${hour2}-${hour1}))*60+(${min2}-${min1}))*60+(${sec2}-${sec1})" )
MATH(EXPR minutes "${diff}/60" )
MESSAGE( "   Time elapsed: ${minutes} minutes" )
