# This will configure and build Draco
# User can configure the source path by specifying DRACO_SRC_DIR,
#    the download path by specifying DRACO_URL, or the installed
#    location by specifying DRACO_INSTALL_DIR


# Default to Draco 7.22.0 unless the caller supplies a source or installation.
IF ( NOT DRACO_URL AND NOT DRACO_SRC_DIR AND NOT DRACO_INSTALL_DIR )
    SET( DRACO_URL "https://github.com/lanl/Draco/archive/refs/tags/draco-7_22_0.tar.gz" )
ENDIF()

# Initialize download/src/install vars
SET( DRACO_BUILD_DIR "${CMAKE_BINARY_DIR}/DRACO-prefix/src/DRACO-build" )
IF ( DRACO_URL )
    MESSAGE("   DRACO_URL = ${DRACO_URL}")
    SET( DRACO_SRC_DIR "${CMAKE_BINARY_DIR}/DRACO-prefix/src/DRACO-src" )
    SET( DRACO_CMAKE_URL          "${DRACO_URL}"     )
    SET( DRACO_CMAKE_DOWNLOAD_DIR "${DRACO_SRC_DIR}" )
    SET( DRACO_CMAKE_SOURCE_DIR   "${DRACO_SRC_DIR}" )
    SET( DRACO_CMAKE_INSTALL_DIR  "${CMAKE_INSTALL_PREFIX}/draco" )
    SET( CMAKE_BUILD_DRACO TRUE )
ELSEIF ( DRACO_SRC_DIR )
    VERIFY_PATH("${DRACO_SRC_DIR}")
    MESSAGE("   DRACO_SRC_DIR = ${DRACO_SRC_DIR}")
    SET( DRACO_CMAKE_URL          ""                 )
    SET( DRACO_CMAKE_DOWNLOAD_DIR ""                 )
    SET( DRACO_CMAKE_SOURCE_DIR   "${DRACO_SRC_DIR}" )
    SET( DRACO_CMAKE_INSTALL_DIR  "${CMAKE_INSTALL_PREFIX}/draco" )
    SET( CMAKE_BUILD_DRACO TRUE )
ELSEIF ( DRACO_INSTALL_DIR )
    SET( DRACO_CMAKE_INSTALL_DIR "${DRACO_INSTALL_DIR}" )
    SET( CMAKE_BUILD_DRACO FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify DRACO_SRC_DIR, DRACO_URL, or DRACO_INSTALL_DIR")
ENDIF()
SET( DRACO_INSTALL_DIR "${DRACO_CMAKE_INSTALL_DIR}" )
MESSAGE( "   DRACO_INSTALL_DIR = ${DRACO_INSTALL_DIR}" )


# Configure optional/required TPLs
IF ( NOT USE_MPI )
    MESSAGE( FATAL_ERROR "DRACO with QUO requires MPI. Please configure with USE_MPI=ON." )
ENDIF()
CONFIGURE_DEPENDENCIES( DRACO REQUIRED GSL QUO RANDOM123 )


# Configure Draco
IF ( CMAKE_BUILD_DRACO )
    IF ( ENABLE_SHARED )
        SET( DRACO_LIBRARY_TYPE SHARED )
    ELSE()
        SET( DRACO_LIBRARY_TYPE STATIC )
    ENDIF()
    SET( DRACO_CONFIGURE_OPTIONS )
    FOREACH( arg ${CMAKE_ARGS} )
        LIST( APPEND DRACO_CONFIGURE_OPTIONS "${arg}" )
    ENDFOREACH()
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DCMAKE_INSTALL_PREFIX=${DRACO_INSTALL_DIR}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DDRACO_LIBRARY_TYPE=${DRACO_LIBRARY_TYPE}" )
    # Draco 7.22 sets standards per target using its own cache variables.
    IF ( CMAKE_C_STANDARD )
        LIST( APPEND DRACO_CONFIGURE_OPTIONS "-DDraco_C_LANGUAGE_STANDARD=${CMAKE_C_STANDARD}" )
    ENDIF()
    IF ( CMAKE_CXX_STANDARD )
        LIST( APPEND DRACO_CONFIGURE_OPTIONS "-DDraco_CXX_LANGUAGE_STANDARD=${CMAKE_CXX_STANDARD}" )
    ENDIF()
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DGSL_ROOT_DIR=${GSL_INSTALL_DIR}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DLIBQUO_ROOT_DIR=${QUO_INSTALL_DIR}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DQUO_HOME=${QUO_INSTALL_DIR}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DRANDOM123_INC_DIR=${RANDOM123_INSTALL_DIR}" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DBUILD_TESTING=OFF" )
    SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DUSE_OPENMP=${USE_OPENMP}" )
    IF ( USE_CUDA )
        SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DUSE_GPU=ON" )
        IF ( CMAKE_CUDA_ARCHITECTURES )
            STRING( REPLACE ";" "\\;" DRACO_CUDA_ARCHITECTURES "${CMAKE_CUDA_ARCHITECTURES}" )
            LIST( APPEND DRACO_CONFIGURE_OPTIONS
                "-DCMAKE_CUDA_ARCHITECTURES=${DRACO_CUDA_ARCHITECTURES}"
                "-DCUDA_ARCHITECTURES=${DRACO_CUDA_ARCHITECTURES}" )
        ENDIF()
    ELSEIF ( USE_HIP )
        SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DUSE_GPU=ON" )
        IF ( CMAKE_HIP_ARCHITECTURES )
            STRING( REPLACE ";" "\\;" DRACO_HIP_ARCHITECTURES "${CMAKE_HIP_ARCHITECTURES}" )
            LIST( APPEND DRACO_CONFIGURE_OPTIONS
                "-DCMAKE_HIP_ARCHITECTURES=${DRACO_HIP_ARCHITECTURES}"
                "-DHIP_ARCHITECTURES=${DRACO_HIP_ARCHITECTURES}" )
        ENDIF()
    ELSE()
        SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DUSE_GPU=OFF" )
    ENDIF()
    IF ( DISABLE_GOLD )
        SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DDISABLE_GOLD=1" )
    ENDIF()
    IF ( MPIEXEC_EXECUTABLE )
        # MPIEXEC_EXECUTABLE may have been set to a bare command name (e.g.
        # "mpirun" via -DMPIEXEC=mpirun) rather than an absolute path. Draco's
        # own configure resolves it relative to ITS build directory, not
        # PATH, so a bare name silently produces a nonexistent path and
        # breaks MPI vendor detection. Resolve to an absolute path here.
        IF ( IS_ABSOLUTE "${MPIEXEC_EXECUTABLE}" )
            SET( DRACO_MPIEXEC_EXECUTABLE "${MPIEXEC_EXECUTABLE}" )
        ELSE()
            FIND_PROGRAM( DRACO_MPIEXEC_EXECUTABLE NAMES ${MPIEXEC_EXECUTABLE} )
            IF ( NOT DRACO_MPIEXEC_EXECUTABLE )
                MESSAGE( FATAL_ERROR "Unable to resolve MPIEXEC_EXECUTABLE '${MPIEXEC_EXECUTABLE}' to an absolute path in PATH" )
            ENDIF()
        ENDIF()
        SET( DRACO_CONFIGURE_OPTIONS "${DRACO_CONFIGURE_OPTIONS};-DMPIEXEC_EXECUTABLE=${DRACO_MPIEXEC_EXECUTABLE}" )
    ENDIF()
    MESSAGE( "   Draco configure options: ${DRACO_CONFIGURE_OPTIONS}" )
    SET( DRACO_CONFIGURE_COMMAND ${CMAKE_COMMAND} )
    IF ( CMAKE_GENERATOR )
        LIST( APPEND DRACO_CONFIGURE_COMMAND -G "${CMAKE_GENERATOR}" )
    ENDIF()
    IF ( CMAKE_GENERATOR_PLATFORM )
        LIST( APPEND DRACO_CONFIGURE_COMMAND -A "${CMAKE_GENERATOR_PLATFORM}" )
    ENDIF()
    IF ( CMAKE_GENERATOR_TOOLSET )
        LIST( APPEND DRACO_CONFIGURE_COMMAND -T "${CMAKE_GENERATOR_TOOLSET}" )
    ENDIF()
    LIST( APPEND DRACO_CONFIGURE_COMMAND <SOURCE_DIR> ${DRACO_CONFIGURE_OPTIONS} )

    ADD_TPL(
        DRACO
        URL                 "${DRACO_CMAKE_URL}"
        DOWNLOAD_DIR        "${DRACO_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${DRACO_CMAKE_SOURCE_DIR}"
        UPDATE_COMMAND      ""
        BUILD_IN_SOURCE     0
        INSTALL_DIR         "${DRACO_INSTALL_DIR}"
        CONFIGURE_COMMAND   ${DRACO_CONFIGURE_COMMAND}
        BUILD_COMMAND       $(MAKE) install VERBOSE=1
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )

ELSE()
    ADD_TPL_EMPTY( DRACO )
ENDIF()


# Add the appropriate fields to FindTPLs.cmake
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n# Find DRACO\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "IF ( TPLs_FIND_DRACO AND NOT TPLs_DRACO_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( DRACO_INSTALL_DIR \"${DRACO_INSTALL_DIR}\" )\n" )
# Older Draco package configs run compilerEnv/dbsSetupCxx when imported,
# replacing the consumer's compiler flags and language standard. Keep those
# normal variables (and Draco's module search paths) local to the import.
# Imported targets remain visible in the caller's directory after ENDBLOCK.
FILE( APPEND "${FIND_TPLS_CMAKE}" "    BLOCK( SCOPE_FOR VARIABLES )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    LIST( PREPEND CMAKE_MODULE_PATH \"${DRACO_INSTALL_DIR}/cmake\" \"${DRACO_INSTALL_DIR}/cmake/draco\" )\n" )
# Draco exports references to these namespaced targets but does not always
# find the dependencies itself. TPLs::GSL and TPLs::QUO are different targets.
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( NOT TARGET GSL::gsl )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( GSL_ROOT_DIR \"${GSL_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        FIND_PACKAGE( GSL REQUIRED MODULE )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( NOT TARGET LIBQUO::libquo )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( LIBQUO_ROOT_DIR \"${QUO_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( QUO_HOME \"${QUO_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        FIND_PACKAGE( Libquo REQUIRED MODULE )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INC_DIR \"${RANDOM123_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INCLUDE_DIR \"${RANDOM123_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INCLUDE_DIRS \"${RANDOM123_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( DRACO_CMAKE_WARN_DEPRECATED $\{CMAKE_WARN_DEPRECATED} )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( CMAKE_WARN_DEPRECATED FALSE )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( POLICY CMP0148 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        CMAKE_POLICY( PUSH )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        CMAKE_POLICY( SET CMP0148 OLD )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( DRACO_POP_CMP0148 TRUE )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FIND_PACKAGE( draco REQUIRED CONFIG PATHS \"${DRACO_INSTALL_DIR}\" \"${DRACO_INSTALL_DIR}/cmake\" \"${DRACO_INSTALL_DIR}/cmake/draco\" NO_DEFAULT_PATH )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( DRACO_POP_CMP0148 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        CMAKE_POLICY( POP )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        UNSET( DRACO_POP_CMP0148 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( CMAKE_WARN_DEPRECATED $\{DRACO_CMAKE_WARN_DEPRECATED} )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    UNSET( DRACO_CMAKE_WARN_DEPRECATED )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDBLOCK()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( DRACO_INCLUDE_DIR \"${DRACO_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( EXISTS \"${DRACO_INSTALL_DIR}/lib\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( DRACO_LIB_DIR \"${DRACO_INSTALL_DIR}/lib\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ELSEIF ( EXISTS \"${DRACO_INSTALL_DIR}/lib64\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( DRACO_LIB_DIR \"${DRACO_INSTALL_DIR}/lib64\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FILE( GLOB DRACO_LIBRARIES \"$\{DRACO_LIB_DIR}/lib*.a\" \"$\{DRACO_LIB_DIR}/lib*.so\" \"$\{DRACO_LIB_DIR}/lib*.dylib\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ADD_TPL_LIBRARY( DRACO $\{DRACO_LIBRARIES} )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n" )
