SET( GSL_BUILD_DIR "${CMAKE_BINARY_DIR}/GSL-prefix/src/GSL-build" )
IF ( GSL_URL )
	MESSAGE("    GSL_URL = ${GSL_URL}")
	SET( GSL_CMAKE_URL          "${GSL_URL}" )
	SET( GSL_CMAKE_DOWNLOAD_DIR "${GSL_BUILD_DIR}" )
	SET( GSL_CMAKE_SOURCE_DIR   "${GSL_BUILD_DIR}" )
	SET( GSL_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/gsl" )
	SET( CMAKE_BUILD_GSL TRUE )
ELSEIF ( GSL_SRC_DIR )
    VERIFY_PATH("${GSL_SRC_DIR}")
    MESSAGE("   GSL_SRC_DIR = ${GSL_SRC_DIR}" )
	SET( GSL_CMAKE_URL          "" )
	SET( GSL_CMAKE_DOWNLOAD_DIR "" )
    SET( GSL_CMAKE_SOURCE_DIR   "${GSL_SRC_DIR}" )
    SET( GSL_CMAKE_INSTALL_DIR  "${CMAKE_INSTALL_PREFIX}/gsl" )
    SET( CMAKE_BUILD_GSL TRUE )
ELSEIF ( GSL_INSTALL_DIR )
    SET( GSL_CMAKE_INSTALL_DIR "${GSL_INSTALL_DIR}" )
    SET( CMAKE_BUILD_GSL FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify GSL_SRC_DIR, GSL_URL, or GSL_INSTALL_DIR")
ENDIF()
SET( GSL_INSTALL_DIR "${GSL_CMAKE_INSTALL_DIR}" )

IF ( CMAKE_BUILD_GSL )
    SET( GSL_CONFIGURE_OPTIONS --prefix=${GSL_CMAKE_INSTALL_DIR} )
    IF ( ENABLE_SHARED AND ENABLE_STATIC )
        LIST( APPEND GSL_CONFIGURE_OPTIONS --enable-shared=yes --enable-static=yes )
    ELSEIF ( ENABLE_SHARED )
        LIST( APPEND GSL_CONFIGURE_OPTIONS --enable-shared=yes --enable-static=no )
    ELSEIF ( ENABLE_STATIC )
        LIST( APPEND GSL_CONFIGURE_OPTIONS --enable-shared=no --enable-static=yes )
    ENDIF()

    ADD_TPL(
        GSL
        URL "${GSL_CMAKE_URL}"
		DOWNLOAD_DIR "${GSL_CMAKE_DOWNLOAD_DIR}"
		SOURCE_DIR "${GSL_CMAKE_SOURCE_DIR}"
        UPDATE_COMMAND ""
        CONFIGURE_COMMAND ${GSL_CMAKE_SOURCE_DIR}/configure ${GSL_CONFIGURE_OPTIONS} ${ENV_VARS}
        BUILD_COMMAND $(MAKE) VERBOSE=1
		BUILD_IN_SOURCE 0
		INSTALL_COMMAND $(MAKE) install
        LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_TEST 1 LOG_INSTALL 1
    )
ELSE()
    ADD_TPL_EMPTY( GSL )
ENDIF()

# Add the appropriate fields to FindTPLs.cmake
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n# Find GSL\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "IF ( TPLs_FIND_GSL AND NOT TPLs_GSL_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( GSL_ROOT_DIR \"${GSL_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( GSL_INSTALL_DIR \"${GSL_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( EXISTS \"${GSL_INSTALL_DIR}/lib\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( GSL_LIB_DIR \"${GSL_INSTALL_DIR}/lib\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ELSEIF ( EXISTS \"${GSL_INSTALL_DIR}/lib64\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET( GSL_LIB_DIR \"${GSL_INSTALL_DIR}/lib64\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FIND_LIBRARY( GSL_LIB       NAMES gsl      PATHS $\{GSL_LIB_DIR} NO_DEFAULT_PATH )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FIND_LIBRARY( GSL_CBLAS_LIB NAMES gslcblas PATHS $\{GSL_LIB_DIR} NO_DEFAULT_PATH )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( NOT GSL_LIB OR NOT GSL_CBLAS_LIB )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        MESSAGE(FATAL_ERROR \"GSL library not found in $\{GSL_LIB_DIR}\")\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ADD_TPL_LIBRARY( GSL $\{GSL_LIB} $\{GSL_CBLAS_LIB} )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n" )
