# This will configure and build kokkos
# User can configure the source path by specifying KOKKOSKERNELS_SRC_DIR,
#    the download path by specifying KOKKOSKERNELS_URL, or the installed 
#    location by specifying KOKKOSKERNELS_INSTALL_DIR


# Check if we have an external Trilinos (we will build Kokkos through it)
SET( TRILINOS_KOKKOSKERNELS )
IF ( KOKKOSKERNELS_INSTALL_DIR )
    SET( TRILINOS_KOKKOSKERNELS FALSE )
ELSE()  
    LIST( FIND TPL_LIST "TRILINOS" index_trilinos )
   IF ( ${index_trilinos} GREATER -1 )
       SET( TRILINOS_KOKKOSKERNELS TRUE )
     ENDIF()
ENDIF()
IF ( ( KOKKOSKERNELS_URL OR KOKKOSKERNELS_SRC_DIR ) AND TRILINOS_KOKKOSKERNELS )
    MESSAGE( FATAL_ERROR "Cannot build Trilinos and external KokkosKernels."
             "   Please remove Trilinos or KOKKOSKERNELS_URL/KOKKOSKERNELS_SRC_DIR" )
ENDIF()


# Intialize download/src/install vars
SET( KOKKOSKERNELS_BUILD_DIR "${CMAKE_BINARY_DIR}/KOKKOSKERNELS-prefix/src/KOKKOSKERNELS-build" )
IF ( KOKKOSKERNELS_URL ) 
    SET( KOKKOSKERNELS_SRC_DIR "${CMAKE_BINARY_DIR}/KOKKOSKERNELS-prefix/src/KOKKOSKERNELS-src" )
    SET( KOKKOSKERNELS_CMAKE_URL            "${KOKKOSKERNELS_URL}"       )
    SET( KOKKOSKERNELS_CMAKE_DOWNLOAD_DIR   "${KOKKOSKERNELS_SRC_DIR}" )
    SET( KOKKOSKERNELS_CMAKE_SOURCE_DIR     "${KOKKOSKERNELS_SRC_DIR}" )
    SET( KOKKOSKERNELS_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/kokkoskernels" )
    SET( CMAKE_BUILD_KOKKOSKERNELS TRUE )
ELSEIF ( KOKKOSKERNELS_SRC_DIR )
    VERIFY_PATH("${KOKKOSKERNELS_SRC_DIR}")
    SET( KOKKOSKERNELS_CMAKE_URL            ""   )
    SET( KOKKOSKERNELS_CMAKE_DOWNLOAD_DIR   "" )
    SET( KOKKOSKERNELS_CMAKE_SOURCE_DIR     "${KOKKOSKERNELS_SRC_DIR}" )
    SET( KOKKOSKERNELS_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/kokkoskernels" )
    SET( CMAKE_BUILD_KOKKOSKERNELS TRUE )
ELSEIF ( TRILINOS_KOKKOSKERNELS )
    SET( KOKKOSKERNELS_CMAKE_URL            "" )
    SET( KOKKOSKERNELS_CMAKE_DOWNLOAD_DIR   "" )
    SET( KOKKOSKERNELS_CMAKE_SOURCE_DIR     "${TRILINOS_CMAKE_SOURCE_DIR}/packages/kokkoskernels" )
    SET( KOKKOSKERNELS_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/trilinos" )
    SET( CMAKE_BUILD_KOKKOSKERNELS FALSE )
ELSEIF ( KOKKOSKERNELS_INSTALL_DIR ) 
    SET( KOKKOSKERNELS_CMAKE_INSTALL_DIR "${KOKKOSKERNELS_INSTALL_DIR}" )
    SET( CMAKE_BUILD_KOKKOSKERNELS FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify KOKKOSKERNELS_SRC_DIR, KOKKOSKERNELS_URL, or KOKKOSKERNELS_INSTALL_DIR")
ENDIF()
IF ( TRILINOS_KOKKOSKERNELS )
    SET( KOKKOSKERNELS_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/trilinos" )
ELSE()
    SET( KOKKOSKERNELS_INSTALL_DIR "${KOKKOSKERNELS_CMAKE_INSTALL_DIR}" )
ENDIF()
MESSAGE( "   KOKKOSKERNELS_URL = ${KOKKOSKERNELS_URL}" )
MESSAGE( "   KOKKOSKERNELS_SRC_DIR = ${KOKKOSKERNELS_SRC_DIR}" )
MESSAGE( "   KOKKOSKERNELS_INSTALL_DIR = ${KOKKOSKERNELS_INSTALL_DIR}" )

# Configure optional/required TPLs
CONFIGURE_DEPENDENCIES( KOKKOSKERNELS KOKKOS )

# Build kokkos
IF ( CMAKE_BUILD_KOKKOSKERNELS )
    MESSAGE( FATAL_ERROR "TPL-Builder cannot install KokkosKernels from source at present ")
ELSE()
    ADD_TPL_EMPTY( KOKKOSKERNELS )
ENDIF()

# Add the appropriate fields to FindTPLs.cmake
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n# Find KOKKOSKERNELS\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "IF ( TPLs_FIND_KOKKOSKERNELS AND NOT TPLs_KOKKOSKERNELS_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FIND_PACKAGE( KokkosKernels REQUIRED PATHS \"${KOKKOSKERNELS_INSTALL_DIR}\" COMPONENTS separable_compilation )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( TARGET Kokkos::kokkoskernels )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET_TARGET_PROPERTIES(Kokkos::kokkoskernels PROPERTIES INTERFACE_COMPILE_OPTIONS \"\" INTERFACE_LINK_OPTIONS \"\")\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( KOKKOSKERNELS_INSTALL_DIR \"${KOKKOSKERNELS_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( KOKKOSKERNELS_INCLUDE_DIR \"${KOKKOSKERNELS_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ADD_TPL_LIBRARY( KOKKOSKERNELS Kokkos::kokkoskernels )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n" )

