# This will configure and build pybind11
# User can configure the source path by specifying PYBIND11_SRC_DIR,
#    the download path by specifying PYBIND11_URL, or the installed
#    location by specifying PYBIND11_INSTALL_DIR


# Intialize download/src/install vars
SET( PYBIND11_BUILD_DIR "${CMAKE_BINARY_DIR}/PYBIND11-prefix/src/PYBIND11-build" )
IF ( PYBIND11_URL )
    MESSAGE("   PYBIND11_URL = ${PYBIND11_URL}")
    SET( PYBIND11_SRC_DIR "${CMAKE_BINARY_DIR}/PYBIND11-prefix/src/PYBIND11-src" )
    SET( PYBIND11_CMAKE_URL            "${PYBIND11_URL}"       )
    SET( PYBIND11_CMAKE_DOWNLOAD_DIR   "${PYBIND11_SRC_DIR}" )
    SET( PYBIND11_CMAKE_SOURCE_DIR     "${PYBIND11_SRC_DIR}" )
    SET( PYBIND11_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/pybind11" )
    SET( CMAKE_BUILD_PYBIND11 TRUE )
ELSEIF ( PYBIND11_SRC_DIR )
    VERIFY_PATH("${PYBIND11_SRC_DIR}")
    MESSAGE("   PYBIND11_SRC_DIR = ${PYBIND11_SRC_DIR}")
    SET( PYBIND11_CMAKE_URL            ""   )
    SET( PYBIND11_CMAKE_DOWNLOAD_DIR   "" )
    SET( PYBIND11_CMAKE_SOURCE_DIR     "${PYBIND11_SRC_DIR}" )
    SET( PYBIND11_CMAKE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/pybind11" )
    SET( CMAKE_BUILD_PYBIND11 TRUE )
ELSEIF ( PYBIND11_INSTALL_DIR )
    SET( PYBIND11_CMAKE_INSTALL_DIR "${PYBIND11_INSTALL_DIR}" )
    SET( CMAKE_BUILD_PYBIND11 FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify PYBIND11_SRC_DIR, PYBIND11_URL, or PYBIND11_INSTALL_DIR")
ENDIF()
SET( PYBIND11_INSTALL_DIR "${PYBIND11_CMAKE_INSTALL_DIR}" )
MESSAGE( "   PYBIND11_INSTALL_DIR = ${PYBIND11_INSTALL_DIR}" )

# Configure pybind11
IF ( CMAKE_BUILD_PYBIND11 )
    SET( PYBIND11_CONFIGURE_OPTIONS ${CMAKE_ARGS} )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -DCMAKE_INSTALL_PREFIX=${PYBIND11_CMAKE_INSTALL_DIR} )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -DPYBIND11_INSTALL=ON )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -DPYBIND11_TEST=OFF )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -B${PYBIND11_BUILD_DIR} )
    SET( PYBIND11_CONFIGURE_OPTIONS ${PYBIND11_CONFIGURE_OPTIONS} -H${PYBIND11_CMAKE_SOURCE_DIR} )
    MESSAGE("   PYBIND11 configure options: ${PYBIND11_CONFIGURE_OPTIONS}")
ENDIF()


# Build pybind11
IF ( CMAKE_BUILD_PYBIND11 )
    ADD_TPL(
        PYBIND11
        URL                 "${PYBIND11_CMAKE_URL}"
        DOWNLOAD_DIR        "${PYBIND11_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${PYBIND11_CMAKE_SOURCE_DIR}"
        UPDATE_COMMAND      ""
        CMAKE_ARGS          ${PYBIND11_CONFIGURE_OPTIONS}
        BUILD_COMMAND       cmake --build ${PYBIND11_BUILD_DIR} --target install -j 8
        BUILD_IN_SOURCE     0
        INSTALL_COMMAND     ""
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )
ELSE()
    ADD_TPL_EMPTY( PYBIND11 )
ENDIF()

# Add the appropriate fields to FindTPLs.cmake
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n# Find PYBIND11\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "IF ( TPLs_FIND_PYBIND11 AND NOT TPLs_PYBIND11_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( Python3_FOUND AND NOT Python_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        FIND_PACKAGE( Python3 REQUIRED COMPONENTS Interpreter Development )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ELSE()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        FIND_PACKAGE( Python REQUIRED COMPONENTS Interpreter Development )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    FIND_PACKAGE( pybind11 REQUIRED CONFIG PATHS \"${PYBIND11_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( PYBIND11_INSTALL_DIR \"${PYBIND11_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( PYBIND11_INCLUDE_DIR $\{pybind11_INCLUDE_DIRS} )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ADD_TPL_LIBRARY( PYBIND11 pybind11::pybind11 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n" )
