# This will configure and install Random123 (header-only)
# User can configure the source path by specifying RANDOM123_SRC_DIR,
#    the download path by specifying RANDOM123_URL, or the installed
#    location by specifying RANDOM123_INSTALL_DIR


# Intialize download/src/install vars
SET( RANDOM123_BUILD_DIR "${CMAKE_BINARY_DIR}/RANDOM123-prefix/src/RANDOM123-build" )
IF ( RANDOM123_URL )
    MESSAGE("   RANDOM123_URL = ${RANDOM123_URL}")
    SET( RANDOM123_CMAKE_URL          "${RANDOM123_URL}"     )
    SET( RANDOM123_CMAKE_DOWNLOAD_DIR "${RANDOM123_BUILD_DIR}" )
    SET( RANDOM123_CMAKE_SOURCE_DIR   "${RANDOM123_BUILD_DIR}" )
    SET( RANDOM123_CMAKE_INSTALL_DIR  "${CMAKE_INSTALL_PREFIX}/random123" )
    SET( CMAKE_BUILD_RANDOM123 TRUE )
ELSEIF ( RANDOM123_SRC_DIR )
    VERIFY_PATH("${RANDOM123_SRC_DIR}")
    MESSAGE("   RANDOM123_SRC_DIR = ${RANDOM123_SRC_DIR}")
    SET( RANDOM123_CMAKE_URL          ""   )
    SET( RANDOM123_CMAKE_DOWNLOAD_DIR "" )
    SET( RANDOM123_CMAKE_SOURCE_DIR   "${RANDOM123_SRC_DIR}" )
    SET( RANDOM123_CMAKE_INSTALL_DIR  "${CMAKE_INSTALL_PREFIX}/random123" )
    SET( CMAKE_BUILD_RANDOM123 TRUE )
ELSEIF ( RANDOM123_INSTALL_DIR )
    SET( RANDOM123_CMAKE_INSTALL_DIR "${RANDOM123_INSTALL_DIR}" )
    SET( CMAKE_BUILD_RANDOM123 FALSE )
ELSE()
    MESSAGE(FATAL_ERROR "Please specify RANDOM123_SRC_DIR, RANDOM123_URL, or RANDOM123_INSTALL_DIR")
ENDIF()
SET( RANDOM123_INSTALL_DIR "${RANDOM123_CMAKE_INSTALL_DIR}" )
MESSAGE( "   RANDOM123_INSTALL_DIR = ${RANDOM123_INSTALL_DIR}" )


# Random123 is header-only: there is nothing to configure or compile, just
# copy the "include" directory to the install prefix.
IF ( CMAKE_BUILD_RANDOM123 )
    ADD_TPL(
        RANDOM123
        URL                 "${RANDOM123_CMAKE_URL}"
        DOWNLOAD_DIR        "${RANDOM123_CMAKE_DOWNLOAD_DIR}"
        SOURCE_DIR          "${RANDOM123_CMAKE_SOURCE_DIR}"
        UPDATE_COMMAND      ""
        CONFIGURE_COMMAND   ls "${RANDOM123_CMAKE_SOURCE_DIR}"
        BUILD_COMMAND       ls "${RANDOM123_CMAKE_SOURCE_DIR}"
        BUILD_IN_SOURCE     0
        INSTALL_COMMAND     ${CMAKE_COMMAND} -E copy_directory "${RANDOM123_CMAKE_SOURCE_DIR}/include"
                             "${RANDOM123_CMAKE_INSTALL_DIR}/include"
        LOG_DOWNLOAD 1   LOG_UPDATE 1   LOG_CONFIGURE 1   LOG_BUILD 1   LOG_TEST 1   LOG_INSTALL 1
    )
ELSE()
    ADD_TPL_EMPTY( RANDOM123 )
ENDIF()


# Add the appropriate fields to FindTPLs.cmake
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n# Find RANDOM123\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "IF ( TPLs_FIND_RANDOM123 AND NOT TPLs_RANDOM123_FOUND )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INSTALL_DIR \"${RANDOM123_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INC_DIR \"${RANDOM123_INSTALL_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INCLUDE_DIR \"${RANDOM123_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    SET( RANDOM123_INCLUDE_DIRS \"${RANDOM123_INSTALL_DIR}/include\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( NOT EXISTS \"$\{RANDOM123_INCLUDE_DIR}/Random123/threefry.h\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        MESSAGE(FATAL_ERROR \"Random123 headers not found in $\{RANDOM123_INCLUDE_DIR}\")\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    IF ( NOT TARGET TPLs::RANDOM123 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        ADD_LIBRARY( TPLs::RANDOM123 INTERFACE IMPORTED )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "        SET_TARGET_PROPERTIES( TPLs::RANDOM123 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"$\{RANDOM123_INCLUDE_DIR}\" )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "    ADD_TPL_LIBRARY( RANDOM123 TPLs::RANDOM123 )\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "ENDIF()\n" )
FILE( APPEND "${FIND_TPLS_CMAKE}" "\n" )
