IF ( EXISTS "${TPL}-done" )
    MESSAGE( "${TPL} completed: ")
    SET( filename "${CMAKE_CURRENT_SOURCE_DIR}/time" )
    IF ( EXISTS "${filename}" )
        INCLUDE( "${CMAKE_CURRENT_LIST_DIR}/print_elapsed.cmake" )
    ENDIF()
ELSE()
    MESSAGE( FATAL_ERROR "${TPL} did not complete")
ENDIF()
