IF ( EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/Testing/Temporary" )
    FILE( GLOB BuildLogs "${CMAKE_CURRENT_SOURCE_DIR}/Testing/Temporary/LastBuild_*.log" )
    LIST( LENGTH BuildLogs len )
    IF ( ${len} EQUAL 0 ) 
        MESSAGE( FATAL_ERROR "No build logs detected" )
    ENDIF()
    FOREACH( file ${BuildLogs} )
        FILE(READ "${file}" contents)
        STRING(REGEX REPLACE ";" "\\\\;" contents "${contents}")
        MESSAGE("${file}:\n${contents}")
        STRING(TOLOWER "${contents}" lower )
        STRING(FIND "${lower}" "error" index )
        LIST( LENGTH index N_errors )
        IF ( NOT( ${index} EQUAL -1 ) )
            MESSAGE(FATAL_ERROR "Errors detected")
        ENDIF()
    ENDFOREACH()
ELSE()
    MESSAGE(FATAL_ERROR "No testing directory detected")
ENDIF()
MESSAGE("No errors detected")

