# FindSAMRAI
# ---------
#
# Find SAMRAI
#
# Use this module by invoking find_package with the form:
#
#   find_package( SAMRAI [REQUIRED] )
#
# This module finds SAMRAI and configures a test using the provided options
#
# This program recognizes the following options
#   SAMRAI_INSTALL_DIR          - Path where SAMRAI is installed ( must be set )
#
# The following variables are set by find_package( SAMRAI )
#
#   SAMRAI_FOUND                - True if SAMRAI was found
#   SAMRAI_LIBS                 - SAMRAI libraries

# Find SAMRAI if available
IF ( NOT SAMRAI_INSTALL_DIR )
    MESSAGE( FATAL_ERROR "SAMRAI_INSTALL_DIR must be set" )
ENDIF()
SET( SAMRAI_INCLUDE_DIR "${SAMRAI_INSTALL_DIR}/include" )
SET( SAMRAI_LIB_DIR "${SAMRAI_INSTALL_DIR}/lib" )

# Find the SAMRAI LIBRARIES
FIND_LIBRARY( SAMRAI_ALGS_LIB NAMES SAMRAI_algs PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_APPU_LIB NAMES SAMRAI_appu PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_GEOM_LIB NAMES SAMRAI_geom PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_HIER_LIB NAMES SAMRAI_hier PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_MATH_LIB NAMES SAMRAI_math PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_MESH_LIB NAMES SAMRAI_mesh PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_PDAT_LIB NAMES SAMRAI_pdat PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_SOLV_LIB NAMES SAMRAI_solv PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_TBOX_LIB NAMES SAMRAI_tbox PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
FIND_LIBRARY( SAMRAI_XFER_LIB NAMES SAMRAI_xfer PATHS ${SAMRAI_LIB_DIR} NO_DEFAULT_PATH )
IF ( (NOT SAMRAI_APPU_LIB )
    OR ( NOT SAMRAI_ALGS_LIB )
    OR ( NOT SAMRAI_SOLV_LIB )
    OR ( NOT SAMRAI_GEOM_LIB )
    OR ( NOT SAMRAI_MESH_LIB )
    OR ( NOT SAMRAI_MATH_LIB )
    OR ( NOT SAMRAI_PDAT_LIB )
    OR ( NOT SAMRAI_XFER_LIB )
    OR ( NOT SAMRAI_HIER_LIB )
    OR ( NOT SAMRAI_TBOX_LIB ) )
    MESSAGE( FATAL_ERROR "SAMRAI contribution libraries not found in ${SAMRAI_LIB_DIR}" )
ENDIF()
SET( SAMRAI_LIBS
    ${SAMRAI_APPU_LIB}
    ${SAMRAI_ALGS_LIB}
    ${SAMRAI_SOLV_LIB}
    ${SAMRAI_GEOM_LIB}
    ${SAMRAI_MESH_LIB}
    ${SAMRAI_MATH_LIB}
    ${SAMRAI_PDAT_LIB}
    ${SAMRAI_XFER_LIB}
    ${SAMRAI_HIER_LIB}
    ${SAMRAI_TBOX_LIB} )
SET( SAMRAI_FORTDIR ${SAMRAI_INSTALL_DIR}/include )

# Read the configure file
SET( SAMRAI_CONFIG_FILE "${SAMRAI_INCLUDE_DIR}/SAMRAI/SAMRAI_config.h" )
FILE( READ "${SAMRAI_CONFIG_FILE}" CONFIG_CONTENTS )
STRING( REPLACE "\r\n" "\n" CONFIG_CONTENTS "${CONFIG_CONTENTS}" ) # Normalize line endings
STRING( REPLACE "\r" "\n" CONFIG_CONTENTS "${CONFIG_CONTENTS}" )
STRING( REGEX REPLACE "\n$" "" CONFIG_CONTENTS "${CONFIG_CONTENTS}" ) # Trim trailing newline
STRING( REPLACE "\n" ";" CONFIG_LINES "${CONFIG_CONTENTS}" )
FOREACH( line IN LISTS CONFIG_LINES )
    # Match lines like: #define NAME VALUE
    SET( NAME )
    SET( VALUE )
    IF ( line MATCHES "^#define[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]+(.+)$" )
        SET( NAME "${CMAKE_MATCH_1}" )
        SET( VALUE "${CMAKE_MATCH_2}" )
        STRING( REGEX REPLACE "^\"( .* )\"$" "\\1" VALUE "${VALUE}" )
        IF ( NOT ( "${NAME}" MATCHES "SAMRAI_" ) )
            SET( NAME "SAMRAI_${NAME}" )
        ENDIF()
    ELSEIF ( line MATCHES "^#define[ \t]+([A-Za-z_][A-Za-z0-9_]*)$" )
        SET( NAME "${CMAKE_MATCH_1}" )
        IF ( NOT ( "${NAME}" MATCHES "SAMRAI_" ) )
            SET( NAME "SAMRAI_${NAME}" )
        ENDIF()
        SET( VALUE TRUE )
    ENDIF()
    IF ( NAME )
        SET( ${NAME} "${VALUE}" )
        #MESSAGE( STATUS "Found define: ${NAME}: ${${NAME}}" )
    ENDIF()
ENDFOREACH()
